#!/usr/bin/env bash

# Check if the bucket name is provided
if [ -z "$1" ]; then
    echo "You should specify the bucket name, e.g., my-bucket-example"
    exit 1
fi

bucketName="$1"

# Confirm with the user before deleting all objects
read -p "Are you sure you want to delete all objects from the bucket '$bucketName'? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "Aborted."
    exit 0
fi

# Delete all objects from the bucket
# https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3/rm.html
aws s3 rm "s3://$bucketName" --recursive

