#!/usr/bin/env bash

#check if the name of the bucket is passed in
if [ -z "$1" ]; then
    echo "You should specify the bucket name, e.g., my-bucket-example"
    exit 1
fi

bucketName=$1

#https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3api/create-bucket.html
aws s3api delete-bucket --bucket $bucketName
