#!/usr/bin/env bash

#check if the name of the bucket is passed in
if [ -z "$1" ]; then
    echo "You should specify the bucket name, e.g., my-bucket-example"
    exit 1
fi

bucketName=$1

# Confirm with the user before deleting the bucket
read -p "Are you sure you want to delete the bucket '$bucketName'? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "Aborted."
    exit 0
fi

#https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3api/delete-bucket.html
#deleting the bucket
aws s3api delete-bucket --bucket $bucketName

if [ $? -eq 0 ]; then
    echo "bucket '$bucketName' deleted."
else
    echo "Failed to delete the bucket."
    exit 1
fi