#!/usr/bin/env bash

# Check if the bucket name is provided
if [ -z "$1" ]; then
    echo "You should specify the bucket name, e.g., my-bucket-example"
    exit 1
fi

bucketName=$1

# List all objects in the bucket using s3api
# https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3api/list-objects.html
aws s3api list-objects --bucket "$bucketName"

# List all objects in the bucket using s3
# https://awscli.amazonaws.com/v2/documentation/api/2.0.34/reference/s3/ls.html
aws s3 ls s3://"$bucketName"